"""
Django settings for resume_backend project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# VS Code and some Windows editors may save .env files with a UTF-8 BOM.
# utf-8-sig strips it so the first variable name (often GEMINI_API_KEY)
# is not loaded as "\ufeffGEMINI_API_KEY".
load_dotenv(BASE_DIR / '.env', encoding='utf-8-sig')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-key-change-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get(
    'DJANGO_DEBUG',
    'False' if os.environ.get('VERCEL') == '1' else 'True',
).lower() in {'1', 'true', 'yes'}
IS_PRODUCTION = os.environ.get('VERCEL') == '1' or not DEBUG

def env_list(name, default=''):
    return [value.strip() for value in os.environ.get(name, default).split(',') if value.strip()]


ALLOWED_HOSTS = env_list('APP_ALLOWED_HOSTS', 'localhost,127.0.0.1' if not IS_PRODUCTION else '')

if IS_PRODUCTION:
    required_production_values = {
        'DJANGO_SECRET_KEY': os.environ.get('DJANGO_SECRET_KEY', ''),
        'DATABASE_URL': os.environ.get('DATABASE_URL', ''),
        'APP_ALLOWED_HOSTS': os.environ.get('APP_ALLOWED_HOSTS', ''),
        'CORS_ALLOWED_ORIGINS': os.environ.get('CORS_ALLOWED_ORIGINS', ''),
        'CSRF_TRUSTED_ORIGINS': os.environ.get('CSRF_TRUSTED_ORIGINS', ''),
        'PDF_RENDER_ORIGIN': os.environ.get('PDF_RENDER_ORIGIN', ''),
        'PDF_RENDER_ALLOWED_ORIGINS': os.environ.get('PDF_RENDER_ALLOWED_ORIGINS', ''),
    }
    missing = [name for name, value in required_production_values.items() if not value.strip()]
    if missing:
        raise ImproperlyConfigured(f"Missing required production environment variables: {', '.join(missing)}")
    if any('://' in host or '/' in host for host in ALLOWED_HOSTS):
        raise ImproperlyConfigured('APP_ALLOWED_HOSTS must contain hostnames only, without schemes or paths.')
    if SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 40:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be a unique value of at least 40 characters in production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'resume_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resume_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def postgres_config(database_url):
    parsed = urlparse(database_url)
    options = dict(parse_qsl(parsed.query))
    options.setdefault('sslmode', 'require')

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': parsed.port or 5432,
        'OPTIONS': options,
        'CONN_MAX_AGE': 0,
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }


DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
USE_SQLITE = os.environ.get('USE_SQLITE', '').lower() in {'1', 'true', 'yes'}
DATABASES = {
    'default': postgres_config(DATABASE_URL) if DATABASE_URL and not USE_SQLITE else {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = IS_PRODUCTION
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Disable APPEND_SLASH to prevent Django from redirecting POST requests.
# On Vercel, a 301 redirect turns POST into GET, which causes a 405 error.
APPEND_SLASH = False

REST_FRAMEWORK = {}
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('MAX_REQUEST_BYTES', str(2 * 1024 * 1024)))
LOGIN_RATE_LIMIT = int(os.environ.get('LOGIN_RATE_LIMIT', '10'))
LOGIN_RATE_WINDOW_SECONDS = int(os.environ.get('LOGIN_RATE_WINDOW_SECONDS', '900'))
AI_USER_RATE_LIMIT = int(os.environ.get('AI_USER_RATE_LIMIT', '10'))
AI_IP_RATE_LIMIT = int(os.environ.get('AI_IP_RATE_LIMIT', '30'))
AI_RATE_WINDOW_SECONDS = int(os.environ.get('AI_RATE_WINDOW_SECONDS', '86400'))
AI_MAX_REQUEST_BYTES = int(os.environ.get('AI_MAX_REQUEST_BYTES', str(250 * 1024)))
AI_MAX_TEXT_CHARS = int(os.environ.get('AI_MAX_TEXT_CHARS', '100000'))

# Keep local development unrestricted. Vercel sets VERCEL=1 automatically;
# other production hosts should set DEBUG=False. Production defaults to five
# anonymous API requests per day unless the host overrides API_ANON_RATE.
if IS_PRODUCTION:
    REST_FRAMEWORK = {
        'DEFAULT_THROTTLE_CLASSES': [
            'rest_framework.throttling.AnonRateThrottle',
        ],
        'DEFAULT_THROTTLE_RATES': {
            'anon': os.environ.get('API_ANON_RATE', '5/day'),
        },
    }
